# Étape 1 : Build Angular
FROM node:20-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build --prod

# Étape 2 : Serveur Nginx
FROM nginx:alpine

# Copie des fichiers Angular compilés (dossier browser)
COPY --from=build /app/dist/tableau-de-bord/browser/ /usr/share/nginx/html/

# Copie du fichier de configuration Nginx
COPY nginx.frontend.conf /etc/nginx/conf.d/default.conf

EXPOSE 80