# Étape 1 : Builder Angular
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build --prod

# Étape 2 : Nginx pour servir Angular
FROM nginx:alpine

COPY --from=builder /app/dist/tableau-de-bord/browser /usr/share/nginx/html

COPY nginx.frontend.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]